const arr = [
  "424",
  "A Cold Wall*",
  "Acne Studios",
  "Ader Error",
  "adidas",
  "Air Jordan",
  "Alexander McQueen",
  "Ambush",
  "Amiri",
  "Ancuta Sarca",
  "AND1",
  "Ann Demeulemeester",
  "Anonymous Club",
  "Anta",
  "Ari",
  "ASICS",
  "Balenciaga",
  "Balmain",
  "BAPE",
  "Billionaire Boys Club",
  "Birkenstock",
  "Bode",
  "Bottega Veneta",
  "Brooks",
  "Burberry",
  "C2H4",
  "Calvin Klein",
  "Casablanca",
  "CELINE",
  "Champion",
  "Chanel",
  "Chloé",
  "Christian Louboutin",
  "Chrome Hearts",
  "Clarks",
  "Comme Des Garçons",
  "Comme Des Garçons Girl",
  "Comme Des Garçons Homme Plus",
  "Common Projects",
  "Converse",
  "Coperni",
  "Courrèges",
  "Crocs",
  "Curry Brand",
  "Dc",
  "Diadora",
  "Diesel",
  "Dior",
  "Dolce & Gabbana",
  "Dr. Martens",
  "Dries Van Noten",
  "ERL",
  "Ewing",
  "Fear Of God",
  "Fear Of God Essentials",
  "Fendi",
  "Fila",
  "Giuseppe Zanotti",
  "Givenchy",
  "Golden Goose",
  "Gucci",
  "Guidi",
  "HOKA",
  "Jacquemus",
  "Jil Sander",
  "Junya Watanabe",
  "Just Don",
  "JW Anderson",
  "KangaROOS",
  "Karhu",
  "Kenzo",
  "Kiko Kostadinov",
  "Kith",
  "Lanvin",
  "Le Coq Sportif",
  "Lemaire",
  "Li Ning",
  "Loewe",
  "Louis Vuitton",
  "Maison Margiela",
  "Maison Mihara Yasuhiro",
  "Marc Jacobs",
  "Marine Serre",
  "Market",
  "Marni",
  "Martine Rose",
  "MCM",
  "Merrell",
  "Miu Miu",
  "Mizuno",
  "MM6 Maison Margiela",
  "Moncler",
  "MSCHF",
  "New Balance",
  "Nike",
  "Oakley",
  "OAMC",
  "Off White",
  "ON",
  "Onitsuka Tiger",
  "Palm Angels",
  "Paris Saint Germain",
  "Pleasures",
  "Polo Ralph Lauren",
  "Prada",
  "Puma",
  "Raf Simons",
  "Reebok",
  "Reese Cooper",
  "Rhude",
  "Rick Owens",
  "Sacai",
  "Saint Laurent",
  "Salomon",
  "Saucony",
  "Suicoke",
  "Supra",
  "Takashi Murakami",
  "The Attico",
  "The North Face",
  "Timberland",
  "Ugg",
  "Under Armour",
  "Undercover",
  "Valentino",
  "Vans",
  "Veja",
  "Versace",
  "Vetements",
  "Visvim",
  "Yeezy",
  "Yohji Yamamoto",
  "YZY",
];

const mostPopularBrands = ["Nike", "Adidas", "Sin Marca", "Marca nacional"];

function convertArrayToJSON(array: Array<string>) {
  return array.map((name) => ({
    name: name,
    value: name.toLowerCase().replace(/\s+/g, ""),
  }));
}

export const brands = convertArrayToJSON(arr);

export const mostPopularBrandsJSON = convertArrayToJSON(mostPopularBrands);
