const arr =[
    "A BATHING APE®",
    "A BETTER MISTAKE",
    "A Kind of Guise",
    "A Paper Kid",
    "A-COLD-WALL*",
    "A. Lange & Söhne",
    "A. ROEGE HOVE",
    "A.EMERY",
    "A.F.Vandevorst",
    "A.L.C.",
    "A.N.G.E.L.O. Vintage Cult",
    "A.W.A.K.E. Mode",
    "Aalto",
    "AAPE BY *A BATHING APE®",
    "Abra",
    "Absidem",
    "Abysse",
    "AC9",
    "Acler",
    "Acne Studios",
    "ACT Nº1",
    "Adam Lippes",
    "Adeam",
    "Ader Error",
    "adidas",
    "adidas by Stella McCartney",
    "adidas Tennis",
    "adidas Yeezy",
    "Adieu Paris",
    "Adina Reyter",
    "Adriana Degreas",
    "Advisory Board Crystals",
    "AERA",
    "AERON",
    "Aesther Ekme",
    "Aeyde",
    "AFB",
    "AG Jeans",
    "Aganovich",
    "Age of Innocence",
    "Agent Provocateur",
    "AGL",
    "Agnelle",
    "agnès b.",
    "Agnona",
    "AGOLDE",
    "AGR",
    "Agua By Agua Bendita",
    "Ahlem",
    "Ahluwalia",
    "AISLING CAMPS",
    "Aje",
    "AKANSHA SETHI",
    "AKOIA SWIM",
    "Akoni",
    "Akris",
    "Akris Punto",
    "ALABAMA MUSE",
    "Alaïa",
    "Alaïa Pre-Owned",
    "Alan Crocetti",
    "Alanui",
    "Alanui x Moon boot",
    "Alanui X Suicoke",
    "Alberta Ferretti",
    "Alberto Biani",
    "Alberto Fasciani",
    "Alcaçuz",
    "Alchemy",
    "Alejandra Alonso Rojas",
    "Aleksander Siradekian",
    "Aleksandre Akhalkatsishvili",
    "ALEMAIS",
    "Alessandra Rich",
    "alessandro enriquez",
    "ALESSANDRO VIGILANTE",
    "Alessi",
    "Alevì",
    "Alex Perry",
    "ALEXA DE LA CRUZ",
    "Alexa Lixfeld",
    "Alexander McQueen",
    "Alexander McQueen Eyewear",
    "Alexander McQueen Pre-Owned",
    "Alexander Wang",
    "Alexandra Golovanoff",
    "Alexandra Llewellyn",
    "Alexandra Miro",
    "Alexandra Rosier",
    "Alexandre Birman",
    "Alexandre Vauthier",
    "Alexis",
    "alice + olivia",
    "Alice Cicolini",
    "Alice McCall",
    "Alienina",
    "Alighieri",
    "Aliita",
    "ALINKA",
    "Alison Lou",
    "ALIX NYC",
    "All Blues",
    "Allude",
    "Almaz",
    "ALOHAS",
    "alonpi cashmere",
    "Alpha Industries",
    "Altea",
    "ALTRA",
    "altu",
    "Altuzarra",
    "Alysi",
    "Amapô",
    "Amazuìn",
    "AMBIENTEC.",
    "Ambra Maddalena",
    "AMBUSH",
    "Amedeo",
    "Amen",
    "AMEN CANDLES",
    "AMI AMALIA",
    "AMI Paris",
    "Amina Muaddi",
    "Amir Slama",
    "AMIR SLAMA GYM",
    "AMIRI",
    "Amomento",
    "AMOTEA",
    "Amsale",
    "Ana Khouri",
    "Ana Radu",
    "Anabela Chan",
    "Ananya",
    "Anapsara",
    "Ancient Greek Sandals",
    "Ancuta Sarca",
    "and Wander",
    "Andersson Bell",
    "Andrea Bogosian",
    "Andrea Fohrman",
    "ANDREA IYAMAH",
    "Andrea Wazen",
    "Andrea Ya'aqov",
    "ANDREĀDAMO",
    "Andres Gallardo",
    "ANDRES OTALORA",
    "Andrew Gn",
    "Anemos",
    "Anglepoise",
    "ANINE BING",
    "Anissa Kermiche",
    "Anita Ko",
    "Anjuna",
    "Anke Drechsel",
    "Ann Demeulemeester",
    "Ann Demeulemeester X Serax",
    "Anna Karin Karlsson",
    "Anna October",
    "Anna Quan",
    "Anna Sui",
    "Annamode",
    "Annelise Michelson",
    "Annette Ferdinandsen",
    "Anni Lu",
    "Annoushka",
    "Anonymous",
    "Another Tomorrow",
    "ANOUKI",
    "Anrealage",
    "Antonella Rizza",
    "Antonelli",
    "Antonino Valenti",
    "Antonio Barbato",
    "Antonio Bernardo",
    "Antonio Marras",
    "APEDE MOD",
    "APL: ATHLETIC PROPULSION LABS",
    "APM Monaco",
    "Apparis",
    "Aquazzura",
    "Aranaz",
    "Arc'teryx",
    "arch4",
    "ARCS",
    "AREA",
    "ARGOT",
    "Aries",
    "Arizona Love",
    "Arma",
    "Armani Exchange",
    "ARMARIUM",
    "Art Dealer",
    "ARTE",
    "Arteana",
    "Artek",
    "As2ov",
    "Asceno",
    "Ash",
    "Ashish",
    "ASICS",
    "ASPESI",
    "Aspinal Of London",
    "Assouline",
    "Astley Clarke",
    "Aston Studio",
    "Astrid Andersen",
    "Atelier Collector Square",
    "Atlein",
    "Atm Anthony Thomas Melillo",
    "ATP Atelier",
    "Atu Body Couture",
    "Au Départ",
    "Audemars Piguet",
    "Audo",
    "August Sandgren",
    "Auralee",
    "Aurelie Bidermann",
    "Automobili Lamborghini",
    "AUTORE",
    "AUTORE MODA",
    "Autry",
    "Ava Adore",
    "Avant Toi",
    "AVAVAV",
    "Aviù",
    "Axel Arigato",
    "Axenoff Jewellery",
    "Aya Muse",
    "Ayda",
    "AYTM",
    "AZ FACTORY",
    "AZEEZA",
    "Azlee",
    "Aztech Mountain",
    "AZZALIA",
    "Azzi & Osta",
    "B SIDES",
    "B-Low The Belt",
    "b+ab",
    "Ba&Sh",
    "Backes & Strauss",
    "Bacon",
    "Badgley Mischka",
    "BAINA",
    "Baldinini",
    "Balenciaga",
    "Balenciaga Eyewear",
    "Balenciaga Pre-Owned",
    "Ballantyne",
    "Bally",
    "Balmain",
    "Balmain Eyewear",
    "Balmain Kids",
    "Balmain Pre-Owned",
    "Bambah",
    "Bang & Olufsen",
    "Bao Bao Issey Miyake",
    "Baobab Collection",
    "BAPY BY *A BATHING APE®",
    "BAR JEWELLERY",
    "Barba",
    "Barbara Bologna",
    "Barbara Bui",
    "Barbour",
    "Barbour International",
    "Barena",
    "Barrie",
    "BARROW",
    "Barton Perreira",
    "Baruni",
    "Baserange",
    "Bassike",
    "Batsheva",
    "Baum Und Pferdgarten",
    "Baume & Mercier",
    "BAYCO",
    "Bazar Deluxe",
    "BAZZA ALZOUMAN",
    "BCBG Max Azria",
    "BearBrick",
    "Beatrice Di Borbone Vintage",
    "BEATRIZ PALACIOS",
    "BEC + BRIDGE",
    "Begüm Khan",
    "Bell & Ross",
    "Bella Freud",
    "Belle Et Bon Bon",
    "belysa",
    "Benedetta Bruzziches",
    "Benjamin Benmoyal",
    "Bernadette",
    "Bernardaud",
    "Bernhard Willhelm",
    "Bethany Williams",
    "BETTINA VERMILLON",
    "BETTTER",
    "Bevza",
    "Beyond Yoga",
    "Bialetti",
    "BIASIA",
    "Bibi van der Velden",
    "BIKINI LOVERS",
    "Billionaire",
    "Billionaire Boys Club",
    "BIRD & KNOLL",
    "Birkenstock",
    "BITE Studios",
    "Bitossi Home",
    "Biyan",
    "Black Comme Des Garçons",
    "Black Coral",
    "BLACK SUEDE STUDIO",
    "BLACKSAW",
    "Blanca Vita",
    "Blancha",
    "Blancpain",
    "Blauer",
    "Blazé Milano",
    "Bleue Burnham",
    "Bloc Studios",
    "Blue Bird Shoes",
    "BLUE SKY INN",
    "BLUEMARBLE",
    "Blugirl",
    "Blumarine",
    "BODE",
    "Boghossian",
    "Boglioli",
    "BOGNER",
    "BOGNER FIRE+ICE",
    "Bonastre",
    "Bond-eye",
    "BONDI BORN",
    "Bonpoint",
    "Bonsai",
    "BONVO",
    "Bordallo Pinheiro",
    "Bordelle",
    "Borgo De Nor",
    "Boris Bidjan Saberi",
    "Borsalino",
    "Bosa",
    "BOSS",
    "BOSS Kidswear",
    "BOTEH",
    "Both",
    "Botier",
    "Bottega Veneta",
    "Bottega Veneta Pre-Owned",
    "Botter",
    "Botto Giuseppe",
    "Boucheron",
    "Boucheron Eyewear",
    "Boucheron Pre-Owned",
    "Bougeotte",
    "Boutique Moschino",
    "Boy Smells",
    "Boyarovskaya",
    "Boyish Jeans",
    "Boyy",
    "BRAND BLACK",
    "Brandon Maxwell",
    "Braun Watches",
    "Breguet",
    "Breitling",
    "Brigitte",
    "Briglia 1949",
    "Brioni",
    "Briston Watches",
    "Brock Collection",
    "Brøgger",
    "Brooke Gregson",
    "Brunello Cucinelli",
    "Bruno Manetti",
    "Buben & Zorweg",
    "Buccellati",
    "BUDDHA MAMA",
    "Buffalo",
    "Burberry",
    "Burberry Eyewear",
    "Burberry Pre-Owned",
    "Burton",
    "Buttero",
    "BVLA",
    "Bvlgari",
    "Bvlgari Pre-Owned",
    "BY FAR",
    "By Malene Birger",
    "By Pariah",
    "By Walid",
    "BYBORRE",
    "Byredo",
    "byTiMo",
    "C.P. Company",
    "C.P. Company Pre-Owned",
    "C2h4",
    "Cabana",
    "Cadar",
    "CAFÉ KITSUNÉ",
    "Cala de la Cruz",
    "Câllas Milano",
    "Calvin Klein",
    "Calvin Klein Jeans",
    "Calvin Klein Jeans Est. 1978",
    "Calvin Klein Underwear",
    "Cameo & Beyond",
    "Camilla",
    "Camper",
    "CamperLab",
    "Canada Goose",
    "Canadian Club",
    "Canali",
    "Cander",
    "CandleHand",
    "Canessa",
    "CANNARI CONCEPT",
    "Cappellini",
    "CAPRI POSITANO SANDALS",
    "Capsule Eleven",
    "Car Shoe",
    "Cara Cara",
    "Caran d'Ache",
    "Caravana",
    "Carel Paris",
    "Carhartt WIP",
    "Carine Gilson",
    "Cariuma",
    "Carlo Moretti",
    "CARNE BOLLENTE",
    "Carolina Herrera",
    "Caroline Constas",
    "CAROLINE HU",
    "Carrera",
    "Carrera Y Carrera",
    "Cartier",
    "Cartier Eyewear",
    "Carven",
    "Carvil",
    "casa raki",
    "Casablanca",
    "Casadei",
    "Casey Casey",
    "Cashmere In Love",
    "Cassina",
    "Castañer",
    "Catherine Regehr",
    "Cathy Waterman",
    "CAVIA",
    "Cawley Studio",
    "Cazal",
    "Cecilia Prado",
    "Cecilie Bahnsen",
    "Celia B",
    "Celine Daoust",
    "Céline Pre-Owned",
    "Celine Robert",
    "Cenere GB",
    "Cesare Paciotti",
    "CFCL",
    "Champion",
    "CHANEL Pre-Owned",
    "Chantal Thomass",
    "Chaos",
    "Charles Jeffrey Loverboy",
    "Charlott",
    "Charlotte Chesnais",
    "Charlotte Olympia",
    "Charo Ruiz Ibiza",
    "Charriol",
    "Chaumet",
    "Cherevichkiotvichki",
    "Chet Lo",
    "CHIARA BONI La Petite Robe",
    "Chiara Ferragni",
    "Chie Mihara",
    "Chinti & Parker",
    "Chloé",
    "Chloé Eyewear",
    "Chloé Kids",
    "Chloé Pre-Owned",
    "CHOCOOLATE",
    "Chopard",
    "Chopard Eyewear",
    "Chopard Pre-Owned",
    "Chopova Lowena",
    "Christian Dior Pre-Owned",
    "Christian Dior x Susan Caplan",
    "Christian Koban",
    "Christian Lacroix Pre-Owned",
    "Christian Louboutin",
    "Christian Louboutin Pre-Owned",
    "Christian Roth",
    "Christian Wijnants",
    "Christofle",
    "Christopher Esber",
    "Christopher John Rogers",
    "Christopher Kane",
    "Chronoswiss",
    "Chufy",
    "Church's",
    "Cia Marítima",
    "Ciao Lucia",
    "Cinq A Sept",
    "Cinzia Rocca",
    "Circolo 1901",
    "Citizens of Humanity",
    "CK Calvin Klein",
    "Claire English",
    "Clarks",
    "Clarks Originals",
    "Claudie Pierlot",
    "CLEA",
    "Clergerie",
    "Closed",
    "CLOT",
    "Clube Bossa",
    "Co",
    "Coach",
    "Coccinelle",
    "Cody Sanderson",
    "COLE BUXTON",
    "college",
    "Collina Strada",
    "Colmar",
    "Colombo",
    "colville",
    "Commando",
    "Comme Des Garçons",
    "Comme Des Garçons Comme Des Garçons",
    "Comme Des Garçons Girl",
    "Comme des Garçons Homme",
    "Comme des Garçons Homme Plus",
    "Comme Des Garçons Play",
    "Comme Des Garçons Play x Converse",
    "Comme Des Garçons Pre-Owned",
    "Comme Des Garçons Shirt",
    "Comme des Garçons TAO",
    "Comme Des Garçons Wallet",
    "Commission",
    "Common Leisure",
    "Common Projects",
    "Completedworks",
    "CONCEPTO",
    "Conner Ives",
    "Converse",
    "Converse x JW Anderson",
    "COOL T.M",
    "Coperni",
    "Cordova",
    "CORMIO",
    "Cornelian Taurus By Daisuke Iwanaga",
    "Corneliani",
    "CORTE DI KEL",
    "Corum",
    "Costarellos",
    "costume national contemporary",
    "Costumein",
    "Côte&Ciel",
    "Cotton Citizen",
    "Coup De Coeur",
    "Courbet",
    "Courrèges",
    "Courrèges Pre-Owned",
    "Craig Green",
    "CRENSHAW SKATE CLUB",
    "Cristina Savulescu",
    "Cruciani",
    "CRUSH CASHMERE",
    "CU I SEEYOU",
    "Cult Gaia",
    "Culti Milano",
    "Current/Elliott",
    "Cutler & Gross",
    "Cynthia Rowley",
    "D.A.T.E.",
    "D.Exterior",
    "D'ACCORI",
    "D'aniello",
    "D1 Milano",
    "D4.0",
    "Daily Paper",
    "DALILA BARKACHE",
    "Damiani",
    "Dana Rebecca Designs",
    "DANCASSAB",
    "Daniel Arsham",
    "Daniel Wellington",
    "Daniela Gregis",
    "Daniela Villegas",
    "Danielle Guizio",
    "Danton",
    "Daou",
    "Daphine",
    "Dark Park",
    "DARKAI",
    "DARKPARK",
    "Daum",
    "David Koma",
    "David Morris",
    "David Yurman",
    "De Beers Jewellers",
    "De Grisogono",
    "DE JAEGHER",
    "De La Vali",
    "DE SIENA SHOES",
    "Dear Frances",
    "Dee Ocleppo",
    "Déhanche",
    "Deiji Studios",
    "Del Carlo",
    "Del Core",
    "Delada",
    "DELAGE",
    "Delalle",
    "Delfina Delettrez",
    "Dell'oglio",
    "Delpozo",
    "DeMellier",
    "Denimist",
    "DENTRO",
    "DENTS",
    "Department 5",
    "DEPENDANCE",
    "Derek Lam 10 Crosby",
    "DES PHEMMES",
    "Desa 1972",
    "Desmond & Dempsey",
    "Destin",
    "DESTREE",
    "Detaj",
    "Devotion",
    "Di Petsa",
    "Diadora",
    "Diane Kordas",
    "Dice Kayek",
    "Diemme",
    "Diesel",
    "dihn van",
    "Dina Melwani",
    "Dinny Hall",
    "Dinosaur Designs",
    "Dion Lee",
    "Diptyque",
    "Direggio",
    "DISA ALLSOPP",
    "Discord Yohji Yamamoto",
    "District Vision",
    "Dita Eyewear",
    "DiW (Designa Individual Watches)",
    "Djula",
    "DKNY",
    "DL1961",
    "Dodo",
    "DÔEN",
    "Dolce & Gabbana",
    "Dolce & Gabbana DGVIB3",
    "Dolce & Gabbana Eyewear",
    "Dolce & Gabbana Kids",
    "Dolce & Gabbana Pre-Owned",
    "Dolci Follie",
    "DOMREBEL",
    "DONDUP",
    "Donna Karan",
    "Dora Larsen",
    "Dorothee Schumacher",
    "Doublet",
    "Doucal's",
    "Dovetusai",
    "DOWER AND HALL",
    "Dr. Martens",
    "DRAGON DIFFUSION",
    "DRHOPE",
    "DRIES VAN NOTEN",
    "Dries Van Noten Pre-Owned",
    "Drôle De Monsieur",
    "Drome",
    "Drumohr",
    "Dsquared2",
    "Dsquared2 Eyewear",
    "Duncan Taylor",
    "Dundas",
    "Dunhill",
    "DUNST",
    "Durazzi Milano",
    "Dusan",
    "Duskii",
    "Duvetica",
    "DVF Diane von Furstenberg",
    "E.M.",
    "Ea7 Emporio Armani",
    "Each X Other",
    "Eastpak",
    "Ebel",
    "Eberhard & Co",
    "Eberjey",
    "ECCO",
    "Eckhaus Latta",
    "Edhen Milano",
    "Editions Milano",
    "Edward Achour Paris",
    "EÉRA",
    "Ef Collection",
    "EGONlab.",
    "Eight & Bob",
    "Eileen Fisher",
    "El Casco",
    "ELECTRIC & ROSE",
    "Eleventy",
    "ELHANATI",
    "Elie Saab",
    "éliou",
    "Elisabetta Franchi",
    "Elisabetta Franchi La Mia Bambina",
    "Elise Dray",
    "Elleme",
    "Ellery",
    "Emanuele Bicocchi",
    "Emilia Wickstead",
    "Emporio Armani",
    "Emporio Armani Kids",
    "Emporio Sirenuse",
    "Endless Joy",
    "Enfants Riches Déprimés",
    "Enföld",
    "Enterprise Japan",
    "ENTIRE STUDIOS",
    "EO",
    "EPHEMERA",
    "Epos",
    "EQUE.M",
    "Equipment",
    "Erdem",
    "ERES",
    "Erika Cavallini",
    "ERL",
    "Ermanno Ermanno",
    "ERMANNO FIRENZE",
    "Ermanno Scervino",
    "Ernest W. Baker",
    "ESCVDO",
    "Eshvi",
    "Essentiel Antwerp",
    "ESSERE",
    "Established & Sons",
    "ESTER MANAS",
    "Etienne Perret",
    "Etnia Barcelona",
    "Être Cécile",
    "ETRO",
    "ETRO HOME",
    "Etro Pre-Owned",
    "Etudes",
    "Eudon Choi",
    "Eugenia Kim",
    "Evarae",
    "Evi Grintela",
    "extreme cashmere",
    "Eyepetizer",
    "Eyevan7285",
    "Eyewear by David Beckham",
    "EYTYS",
    "F.R.S For Restless Sleepers",
    "Fabiana Filippi",
    "Face À Face",
    "Facetasm",
    "Factory 900",
    "Faith Connexion",
    "Faithfull the Brand",
    "Fake Alpha Vintage",
    "Faliero Sarti",
    "Falke",
    "Family Affair",
    "FARM Rio",
    "Fay",
    "Fay Kids",
    "Fear Of God",
    "FEAR OF GOD ESSENTIALS",
    "FEBEN",
    "Fedeli",
    "Federica Tosi",
    "FEDERICO CINA",
    "Fely Campo",
    "Femme La",
    "FENDI",
    "Fendi Pre-Owned",
    "Feng Chen Wang",
    "Fenty X Puma",
    "Fernando Jorge",
    "Ferragamo",
    "Ferragamo Pre-Owned",
    "Ferrari",
    "Fferrone Design",
    "Figue",
    "FIGURE DECORATIVE",
    "Fila",
    "Fileria",
    "Filippa K",
    "Filles A Papa",
    "Filling Pieces",
    "Filson",
    "Finamore 1925 Napoli",
    "Fiorucci",
    "Fisico",
    "FIVE CM",
    "Flapper",
    "FLATLIST",
    "Fleur Du Mal",
    "Fleur Of England",
    "FLORA BHATTACHARY",
    "Flos",
    "Floyd",
    "Fob Paris",
    "Folies By Renaud",
    "FOPE",
    "For Love And Lemons",
    "Form and Fold",
    "Forme D'expression",
    "Fornasetti",
    "Forte Dei Marmi Couture",
    "Forte Forte",
    "Fortela",
    "FPM Milano",
    "FRAME",
    "Frame Chain",
    "Framed",
    "Francesca Bellavita",
    "Francesca Villa",
    "Francesco Russo",
    "Franck Muller",
    "Frankies Bikinis",
    "Fratelli Rossetti",
    "Fred",
    "FRED LEIGHTON",
    "Fred Perry",
    "Fred Segal",
    "Fredericia Furniture",
    "Frederique Constant",
    "Frenckenberger",
    "Frency & Mercury",
    "Frenken",
    "Frenzlauer",
    "Frescobol Carioca",
    "Fumito Ganryu",
    "Furla",
    "FURLING BY GIANI",
    "Fusalp",
    "G.H. Bass & Co.",
    "G.O.D Eyewear",
    "G/FORE",
    "GABO NAPOLI",
    "Gabriela Hearst",
    "Gabriele Pasini",
    "Gaby Charbachy",
    "Gaelle Khouri",
    "GALLERY DEPT.",
    "Galvan London",
    "GANNI",
    "Gardeco",
    "Garrett Leight",
    "Gauchère",
    "GAUGE81",
    "Gavello",
    "Gaya",
    "Gaydamak",
    "Gcds",
    "Gedebe",
    "Gejst",
    "Gemco",
    "GEMFIELDS X MUSE",
    "Gems N' Crafts",
    "Gemy Maalouf",
    "Genny",
    "Gentle Monster",
    "Gentry Portofino",
    "George Cox",
    "GERGEI ERDEI",
    "Gestuz",
    "Ghidini 1961",
    "GHŌUD",
    "GIA STUDIOS",
    "GIABORGHINI",
    "Giada Benincasa",
    "Giambattista Valli",
    "Gianfranco Ferré Home",
    "Gianfranco Ferré Pre-Owned",
    "Gianluca Capannolo",
    "Giannico",
    "Gianvito Rossi",
    "Gigi Burris Millinery",
    "Gigi Clozeau",
    "GIGI STUDIOS",
    "Gilda & Pearl",
    "Gimaguas",
    "GINETTE NY",
    "GINORI 1735",
    "Giobagnara",
    "Giorgio Armani",
    "Giorgio Armani Pre-Owned",
    "Giorgio Brato",
    "Giovanni Bedin",
    "Girard-Perregaux",
    "Girard-Perregaux Pre-Owned",
    "Girlfriend Collective",
    "Gitman Vintage",
    "Giuliano Galiano",
    "Giuliva Heritage",
    "Giuseppe Di Morabito",
    "Giuseppe Zanotti",
    "Givenchy",
    "Givenchy Eyewear",
    "Givenchy Kids",
    "Givenchy Pre-Owned",
    "Gladys Tamez",
    "Glanshirt",
    "Gloria Coelho",
    "GmbH",
    "Goen.J",
    "GOES BOTANICAL",
    "Gold Hawk",
    "Goldbergh",
    "Golden Goose",
    "GOLDSIGN",
    "Good American",
    "GOODIOUS",
    "Goossens",
    "Goyard Pre-Owned",
    "GR10K",
    "Graf von Faber-Castell",
    "Gramicci",
    "Grand Seiko",
    "Gray Matters",
    "graziela",
    "Greg Lauren",
    "GRETA BOLDINI",
    "Greta Constantine",
    "Grey Mer",
    "Gripoix",
    "gu_de",
    "Gucci",
    "Gucci Eyewear",
    "Gucci Pre-Owned",
    "GUESS USA",
    "Guest In Residence",
    "GUFRAM",
    "Guidi",
    "Gul Hurgel",
    "Gunia Project",
    "Guy Laroche Pre-Owned",
    "Hackett",
    "Haculla",
    "Haeckels",
    "Haider Ackermann",
    "Haikure",
    "Hale Bob",
    "Halfboy",
    "Halmanera",
    "Halpern",
    "Halston",
    "Hamilton Watch",
    "Han Kjøbenhavn",
    "Handred",
    "Hands on design",
    "Hanro",
    "HARDOT",
    "HARRIET MORRIS",
    "Harris Wharf London",
    "Harry Winston",
    "Harwell Godfrey",
    "Hatton Labs",
    "Haus of Honey",
    "HAY",
    "Hayley Menzies",
    "Hebe Studio",
    "Hector Saxe",
    "Hed Mayner",
    "Helen Kaminski",
    "HELIOT EMIL",
    "Helle Mardahl",
    "Hellessy",
    "Helmstedt",
    "Helmut Lang",
    "Helmut Lang Pre-Owned",
    "Hemant And Nandita",
    "Henderson Baracco",
    "Henrik Vibskov",
    "Hereu",
    "Hermès Pre-Owned",
    "Hermina Athens",
    "Herno",
    "Heron Preston",
    "Héros",
    "Herrlicht",
    "HERSKIND",
    "Herve L. Leroux",
    "Hevo",
    "Hide&Jack",
    "HODAKOVA",
    "Hogan",
    "HOKA",
    "Holzweiler",
    "Homme Plissé Issey Miyake",
    "HommeGirls",
    "Honey Fucking Dijon",
    "Honor The Gift",
    "Hood By Air",
    "HOORSENBUHS",
    "Horus Watch Straps",
    "House Of Dagmar",
    "House of Meraki",
    "House of Sunny",
    "hrh",
    "HStern",
    "Hsu Jewellery",
    "Htc Los Angeles",
    "Hublot",
    "Huf",
    "HUGO",
    "Hugo Kreit",
    "Huishan Zhang",
    "hum",
    "HUMA EYEWEAR",
    "Hunter",
    "Hunza G",
    "Hydrogen",
    "Hyein Seo",
    "HYT Jewelry",
    "Hzmer Jewelry",
    "I Love Mr Mittens",
    "I.D. Sarrieri",
    "IBELIV",
    "IBRIGU",
    "Iceberg",
    "ICECREAM",
    "Ichendorf Milano",
    "Ienki Ienki",
    "Ih Nom Uh Nit",
    "iindaco",
    "IIUVO",
    "Il Bisonte",
    "Ilaria Nistri",
    "Ileana Makri",
    "ILIO SMERALDO",
    "IN GOLD WE TRUST PARIS",
    "In The Mood For Love",
    "INBAR",
    "Incentive! Cashmere",
    "Incotex",
    "Inès & Maréchal",
    "Innerraum",
    "Inuikii",
    "Ioana Ciolacu",
    "Ioannes",
    "Iosselliani",
    "IPPOLITA",
    "Irene Neuwirth",
    "IRENEISGOOD",
    "Iris Von Arnim",
    "IRO",
    "Isa Boulder",
    "Isaac Sellam Experience",
    "Isabel Benenato",
    "ISABEL MARANT",
    "Isabel Marant Eyewear",
    "Isabel Sanchis",
    "Isla",
    "Isolda",
    "ISOSCELES",
    "Issey Miyake",
    "Issey Miyake Pre-Owned",
    "It's Now Cool",
    "IVI",
    "IWC Schaffhausen",
    "IXIAH",
    "Izaak Azanei",
    "izzue",
    "J Brand",
    "J Koo",
    "J.Lindeberg",
    "J&M Davidson",
    "Jacob Cohën",
    "Jacqueline Rabun",
    "Jacquemus",
    "Jacques Marie Mage",
    "Jacquie Aiche",
    "Jade Cropper",
    "JADE Swim",
    "Jade Trau",
    "Jaeger-LeCoultre",
    "Jakke",
    "James Perse",
    "JANE",
    "Jaquet Droz",
    "Jason Wu",
    "Jason Wu Collection",
    "JC de Castelbajac Pre-Owned",
    "Jean Francois Mimilla",
    "Jean Louis Scherrer Pre-Owned",
    "Jean Paul Gaultier",
    "Jean Paul Gaultier Pre-Owned",
    "JEAN-LOUIS SABAJI",
    "Jeanerica",
    "Jeff Hamilton",
    "Jeffrey Campbell",
    "Jejia",
    "Jennifer Behr",
    "Jennifer Chamandi",
    "Jennifer Gibson Jewellery",
    "Jennifer Meyer",
    "Jenny Packham",
    "Jérôme Dreyfuss",
    "Jessie Western",
    "JIA JIA",
    "Jil Sander",
    "Jil Sander Pre-Owned",
    "Jimmy Choo",
    "Jimmy Choo Eyewear",
    "Jimmy Choo Pre-Owned",
    "JNBY",
    "Joëlle Jewellery",
    "Johanna Ortiz",
    "JOHANNA PARV",
    "John Elliott",
    "John Galliano Pre-Owned",
    "John Hardy",
    "John Richmond",
    "John Smedley",
    "Johnstons of Elgin",
    "Jonathan Adler",
    "Jordan",
    "Jordan Dalah Studio",
    "JORDANLUCA",
    "Jorg Hysek",
    "Josef Miller",
    "JOSEPH",
    "Joshua Sanders",
    "Judith Leiber",
    "Julien David",
    "Juliet Dunn",
    "JULIETTA",
    "Julius",
    "Juneyen",
    "Junya Watanabe",
    "Junya Watanabe Comme des Garçons Pre-Owned",
    "Just Cavalli",
    "Just Don",
    "Justine Clenquet",
    "Juun.J",
    "JW Anderson",
    "JW Pei",
    "K. Brunini",
    "K. Jacques",
    "Kaleos",
    "Kame Mannen",
    "Kamushki",
    "KANGHYUK",
    "Kansai Yamamoto Pre-Owned",
    "KAPITAL",
    "Kappa",
    "Kara",
    "Karakter",
    "Karen Wazen",
    "Karl Lagerfeld",
    "Karl Lagerfeld Jeans",
    "Karl Lagerfeld Kids",
    "KASK",
    "KASSL Editions",
    "Kasun London",
    "Kate Cate",
    "Kate Spade",
    "Katheleys Vintage",
    "KATHERINE JETTER",
    "KATKIM",
    "KAWS",
    "Kay Bojesen",
    "Kenneth Jay Lane",
    "Kenneth Jay Lane Vintage",
    "Kenzo",
    "Kenzo Pre-Owned",
    "Kerne.Milk",
    "KG Kurt Geiger",
    "KHAITE",
    "KHIRY",
    "Khrisjoy",
    "KidSuper",
    "Kika Vargas",
    "Kiki de Montparnasse",
    "Kiki McDonough",
    "Kiko Kostadinov",
    "Kimaï",
    "Kimberly McDonald",
    "Kimhekim",
    "Kimy Gringoire",
    "Kinraden",
    "Kired",
    "Kirin",
    "Kismet By Milka",
    "Kiton",
    "Kitri",
    "KLIMCHI",
    "knindustrie",
    "KNWLS",
    "Koché",
    "Kolor",
    "Kristensen Du Nord",
    "Krizia Pre-Owned",
    "Ksubi",
    "KTZ",
    "Kuboraum",
    "kujten",
    "Kurt Geiger London",
    "Kvadrat",
    "Kwaidan Editions",
    "KWIAT",
    "KYme",
    "L.A. EYEWORKS",
    "L.G.R",
    "L'Agence",
    "L'Alingi",
    "L'Autre Chose",
    "L'Eclaireur Made By",
    "L'IDÉE",
    "L'Objet",
    "La Collection",
    "La Detresse",
    "La DoubleJ",
    "la milanesa",
    "La Perla",
    "La Petite Lunette Rouge",
    "La Reveche",
    "La Semaine",
    "Laboratorio Paravicini",
    "laCalifornienne",
    "Lack Of Color",
    "Lacoste",
    "LADENAC",
    "LAETITIA ROUGET",
    "Lala Berlin",
    "Lalique",
    "Lama Jouni",
    "Lamberto Losani",
    "Lancel",
    "Laneus",
    "Lanvin",
    "Lanvin Pre-Owned",
    "Lapima",
    "LAPOINTE",
    "LaQuan Smith",
    "Lara Melchior",
    "Lardini",
    "Lark & Berry",
    "Larroude",
    "LASTFRAME",
    "Laura Lombardi",
    "Lauren Manoogian",
    "Lauren Ralph Lauren",
    "Lauren Rubinski",
    "Laurence Dacade",
    "Le 17 Septembre",
    "Le Creuset",
    "Le Gramme",
    "Le Jean",
    "Le Kasha",
    "Le Monde Beryl",
    "LE PETIT TROU",
    "Le Silla",
    "LE STER",
    "Le Tanneur",
    "Le Tricot Perugia",
    "LEBLON DELIENNE",
    "Lebrand",
    "Leclaireur",
    "LEDA MADERA",
    "Lee Mathews",
    "LEGRES",
    "Leisure Society",
    "LEMAIRE",
    "LEMELS",
    "lemlem",
    "Leo Lin",
    "LEO PIZZO",
    "Les Benjamins",
    "Les Girls Les Boys",
    "LES HOMMES",
    "Les Petits Joueurs",
    "Les Tien",
    "Les-Ottomans",
    "Lesca",
    "Leslie Amon",
    "Letanne",
    "Levi's",
    "Levi's: Made & Crafted",
    "LGN LOUIS GABRIEL NOUCHI",
    "Lhd",
    "Li-Ning",
    "Lia Di Gregorio",
    "Liberal Youth Ministry",
    "Lidfort",
    "LIDO",
    "Ligne Blanche",
    "Likely",
    "Lily Montez Vintage",
    "Linda Farrow",
    "Linda Farrow X Magda Butrym",
    "Lindberg",
    "Lisa Corti",
    "Lisa Marie Fernandez",
    "Lisa Von Tang",
    "Lisa Yang",
    "Liska",
    "Litkovskaya",
    "Lito",
    "Little Ones Paris",
    "LIU JO",
    "Live The Process",
    "LIYA",
    "Lizzie Mandler Fine Jewelry",
    "Lladró",
    "LØCI",
    "Loeffler Randall",
    "LOEWE",
    "Loewe Pre-Owned",
    "LOLA MAYERAS",
    "Longchamp",
    "Longines",
    "Longines",
    "Loquet",
    "Loree Rodkin",
    "Loren Stewart",
    "Lorena Antoniazzi",
    "Lorenzi Milano",
    "Loro Piana",
    "Louis Shengtao Chen",
    "Louis Vuitton Pre-Owned",
    "Louisa Ballou",
    "Louise Roe",
    "Loulou",
    "Loulou Studio",
    "Love Moschino",
    "Love Stories",
    "LOVEBIRDS",
    "LOVENESS LEE",
    "LoveShackFancy",
    "Low Brand",
    "Low Classic",
    "Loyal.e Paris",
    "LSA International",
    "LUAR",
    "LUCIFER VIR HONESTUS",
    "Lucy Delius Jewellery",
    "Ludovic de Saint Sernin",
    "LUG VON SIGA",
    "LUIS MORAIS",
    "Luisa Beccaria",
    "Luisa Cerano",
    "Lukhanyo Mdingi",
    "lululemon",
    "LUNARIA CASHMERE",
    "Lunor",
    "LUUDA",
    "LVIR",
    "Lygia & Nanny",
    "M.Cohen",
    "Ma'ry'ya",
    "MAAP",
    "MAC",
    "Macgraw",
    "MACH & MACH",
    "Mackage",
    "Mackintosh",
    "MAD et LEN",
    "MAD Paris",
    "MADE FOR A WOMAN",
    "Made in Tomboy",
    "Madeleine Thompson",
    "MadeWorn",
    "Madison.Maison",
    "Maeden",
    "Magda Butrym",
    "magis",
    "Magliano",
    "Magnanni",
    "Magniberg",
    "Maharishi",
    "Maiami",
    "Mainless",
    "Maisie Wilen",
    "Maison Balzac",
    "Maison Close",
    "Maison Essentiele",
    "Maison Kitsuné",
    "Maison Labiche",
    "Maison Margaux",
    "Maison Margiela",
    "Maison Martin Margiela Pre-Owned",
    "Maison Michel",
    "Maison Mihara Yasuhiro",
    "Maison Rabih Kayrouz",
    "Maison Skorpios",
    "Maison Ullens",
    "Maje",
    "Majestic Filatures",
    "Makavelic",
    "MALIN+GOETZ",
    "Mallet",
    "Malo",
    "Malone Souliers",
    "Mame Kurogouchi",
    "Manebi",
    "MANNING CARTELL",
    "Manokhi",
    "Manolo Blahnik",
    "Mansur Gavriel",
    "Manu Atelier",
    "Manuel Ritz",
    "MANURI",
    "Manzoni 24",
    "MAOR",
    "Mara Hoffman",
    "MARANT ÉTOILE",
    "Marc Jacobs",
    "Marc Jacobs Eyewear",
    "Marc Le Bihan",
    "Marcelo Burlon County of Milan",
    "MARCH LA.B",
    "Marchesa",
    "Marchesa Notte",
    "Marchesa Notte Bridesmaids",
    "Marchesa Rosa",
    "Marcia",
    "Marco Bicego",
    "Marco De Vincenzo",
    "Marco Rambaldi",
    "Margaret Howell",
    "Marge Sherwood",
    "Margherita MACCAPANI",
    "Maria Black",
    "MARIA LUCA",
    "Maria Lucia Hohan",
    "Maria Nilsdotter",
    "MARIA TASH",
    "Marie Lichtenberg",
    "Marina Rinaldi",
    "marina yee",
    "Marine Serre",
    "Mark Davis",
    "MARK KENLY DOMINO TAN",
    "Markarian",
    "MARKET",
    "Markus Lupfer",
    "Marla Aaron",
    "Marlies Dekkers",
    "Marni",
    "Marni Eyewear",
    "Marni Pre-Owned",
    "Marques'Almeida",
    "Marsèll",
    "Marshall Columbia",
    "Marsotto Edizioni",
    "Martha Medeiros",
    "Martin Grant",
    "Martine Ali",
    "Martine Jarlgaard",
    "Martine Rose",
    "Mary Katrantzou",
    "Maryam Nassir Zadeh",
    "MaryJane Claverol",
    "Marysia",
    "MASAHIROMARUYAMA",
    "Masha Popova",
    "Masnada",
    "Mason & Books",
    "Masscob",
    "Massimo Alba",
    "Mastermind Japan",
    "Mastermind World",
    "Masterpeace",
    "Masunaga",
    "Mateo",
    "Materiel",
    "Maticevski",
    "Matsuda",
    "Matteau",
    "Mattia Cielo",
    "Mauboussin",
    "Maui Jim",
    "Mauna Kea",
    "Maurice Lacroix",
    "MAURICE LACROIX PRE-OWNED",
    "Maurizio Miri",
    "MAURIZIO MYKONOS",
    "MAVIADA",
    "Max & Moi",
    "Max Mara",
    "Maximilian Davis",
    "Maybach eyewear",
    "Maygel Coronel",
    "Mazzarelli",
    "MB&F",
    "MC2 Saint Barth",
    "MC2 Saint Barth Kids",
    "MCM",
    "MCQ",
    "McQ Swallow",
    "MDG x CT",
    "Medea",
    "MEDICOM TOY",
    "MEHTAP ELAIDI",
    "Melissa Joy Manning",
    "Melissa Kandiyoti",
    "Melissa Kaye",
    "Melissa Odabash",
    "Melissa x Undercover",
    "Melitta Baumeister",
    "Merci",
    "Merlette",
    "MERYLL ROGGE",
    "Mes Demoiselles",
    "Messika",
    "Miaoran",
    "Miaou",
    "Michael Kors",
    "Michael Kors Collection",
    "Michael Michael Kors",
    "Michael Verheyden",
    "Michel Vivien",
    "Michelle Mason",
    "mii",
    "Miki House",
    "Mikimoto",
    "MILA SCHON",
    "Milly",
    "MIMI",
    "Mindi Mond",
    "Minds",
    "Mira Mikati",
    "Misa Los Angeles",
    "MISBHV",
    "MISCI",
    "MISHA",
    "Missing You Already",
    "Missoma",
    "Missoni",
    "MISSONI EYEWEAR",
    "Missoni Home",
    "Missoni Kids",
    "Missoni Pre-Owned",
    "Miu Miu",
    "Miu Miu Eyewear",
    "Miu Miu Pre-Owned",
    "MIYETTE",
    "Mizuki",
    "Mizuno",
    "MM6 Maison Margiela",
    "MM6 Maison Margiela X Salomon",
    "Moa Master Of Arts",
    "MODES GARMENTS",
    "Moeva",
    "Molly Goddard",
    "Moma",
    "Monan",
    "Moncler",
    "Moncler + Rick Owens",
    "Moncler Eyewear",
    "Moncler Grenoble",
    "Moncler x Poldo",
    "Monet Pre-Owned",
    "MONICA RICH KOSANN",
    "Monica Vinader",
    "Monies",
    "Monique Lhuillier",
    "MONOCHROME",
    "Monocle Eyewear",
    "Mônot",
    "Monse",
    "Montblanc",
    "Moohong",
    "Moon Boot",
    "Moorer",
    "Moose Knuckles",
    "More Joy",
    "Moreau",
    "Moreschi",
    "Morganne Bello",
    "Moritz Glik",
    "Moschino",
    "Moschino Eyewear",
    "MOSCHINO JEANS",
    "Moschino Pre-Owned",
    "Mostly Heard Rarely Seen",
    "Mostly Heard Rarely Seen 8-Bit",
    "MOTHER",
    "Mou",
    "Mou Kids",
    "MOULETA",
    "Mounser",
    "Moussy Vintage",
    "Moustache",
    "Movado",
    "Mr & Mrs Italy",
    "Mr. Mittens",
    "MRZ",
    "MSFTSrep",
    "MSGM",
    "Mugler",
    "Mulberry",
    "Muller Of Yoshiokubo",
    "Mumutane",
    "Munderingskompagniet",
    "MUNTHE",
    "Murmur",
    "Musier",
    "Musium Div.",
    "MUZUNGU SISTERS",
    "Mykita",
    "Myths",
    "N.Peal",
    "NAADAM",
    "Nackiyé",
    "Nada Ghazal",
    "NADIA SHELBAYA",
    "NAGHEDI",
    "NAKED WOLFE",
    "Namacheko",
    "Nannacay",
    "Nanushka",
    "Napa By Martine Rose",
    "Napapijri",
    "NasonMoretti",
    "Natasha Zinko",
    "NATHALIE BLANC PARIS",
    "Natia X Lako",
    "Needle & Thread",
    "Needles",
    "Neighborhood",
    "Neil Barrett",
    "NELLS NELSON",
    "Nensi Dojaka",
    "NEOUS",
    "Neriage",
    "NERVI",
    "Neuw",
    "Nevernot",
    "New Balance",
    "NEW STANDARD",
    "Nialaya Jewelry",
    "Niccolò Pasqualetti",
    "Nicholas",
    "Nicholas Kirkwood",
    "Nicholas Varney",
    "Nick Fouquet",
    "Nicole Benisti",
    "Nicole Saldaña",
    "NICOLI",
    "Niili",
    "Nike",
    "Nike x Ambush",
    "Nike X Off-White",
    "NIKE x SACAI",
    "NIKO JUNE",
    "Nikos Koulis",
    "Nili Lotan",
    "Nina Ricci",
    "Nina Ricci Pre-Owned",
    "Ninamounah",
    "NISSA",
    "Niza Huang",
    "Nk",
    "No Ka' Oi",
    "Nº21",
    "NOAH NY",
    "Nodaleto",
    "Noir Kei Ninomiya",
    "Noire Swimwear",
    "Nomadic State of Mind",
    "Nomos",
    "Noor Fares",
    "norda",
    "NORLHA",
    "NORMA JEWELLERY",
    "Norma Kamali",
    "Normann Copenhagen",
    "Norse Projects",
    "Norwegian Wool",
    "Nouvel Heritage",
    "Nubian Skin",
    "Nubikk",
    "Nude",
    "Nuè",
    "NUMBERING",
    "Numero 10",
    "Nuove Forme",
    "NUUN OFFICIAL",
    "Nuur",
    "Nylora",
    "O Thongthai",
    "Oakley",
    "OAMC",
    "OBJECTS IV LIFE",
    "Oceanus",
    "Octavia Elizabeth",
    "Odeeh",
    "Off-White",
    "Off-White Pre-Owned",
    "Officina Bernardi",
    "Officine Creative",
    "Officine Generale",
    "Oliver Goldsmith",
    "Oliver Peoples",
    "Olivia Rubin",
    "Olivia von Halle",
    "Olympia Le-Tan",
    "Olympiah",
    "Omc",
    "OMEGA",
    "OMEGA EYEWEAR",
    "On Running",
    "On The Island",
    "Once Milano",
    "Onefifteen",
    "Onitsuka Tiger",
    "Onno",
    "Opening Ceremony",
    "OpéraSPORT",
    "Orciani",
    "Organic Basics",
    "Orgreen",
    "Origin Made",
    "Oris",
    "Orlebar Brown",
    "Orolog By Jaime Hayon",
    "Oroton",
    "Oscar de la Renta",
    "Oséree",
    "Osklen",
    "Osoi",
    "Otiumberg",
    "Ottolinger",
    "OUR LEGACY",
    "Outdoor Voices",
    "Overose",
    "Oyuna",
    "OZWALD BOATENG",
    "P.A.R.O.S.H.",
    "P.E Nation",
    "P.L.N.",
    "PACE",
    "Paco Rabanne Pre-Owned",
    "PAIGE",
    "Palace",
    "Palm Angels",
    "Palmer//Harding",
    "Palmes",
    "Paloma Barceló",
    "Paloma Wool",
    "Paltò",
    "Pamella Roland",
    "Panconesi",
    "Panerai",
    "Pangaia",
    "Pantos Paris",
    "Paola Sighinolfi",
    "Paolina Russo",
    "Paolo Piovan",
    "Papa Oppong",
    "Paper London",
    "Paraboot",
    "Paradis Collection",
    "Parajumpers",
    "PARAMIDONNA",
    "Paria Farzaneh",
    "Paris Georgia",
    "Paris Texas",
    "Parlor",
    "Partow",
    "Parts of Four",
    "Pas Normal Studios",
    "Pascale Monvoisin",
    "Pascia",
    "Pasquale Bruni",
    "Patagonia",
    "PatBO",
    "Patek Philippe",
    "Patou",
    "Patrizia Pepe",
    "Paul Andrew",
    "Paul Smith",
    "Paul Warmer",
    "PAULA",
    "Paula Canovas del Vas",
    "Paula Knorr",
    "Paule Ka",
    "Paura",
    "Pearl Octopuss. Y",
    "PEARLY GATES",
    "Pedro Garcia",
    "Pendleton",
    "Penelope Chilvers",
    "PENINSULA SWIMWEAR",
    "peony",
    "PEPA SALAZAR",
    "Pequignet",
    "Perfect Moment",
    "Perks And Mini",
    "Perrin Paris",
    "Persée",
    "Persol",
    "Peserico",
    "Petar Petrov",
    "Peter & May Walk",
    "Peter Cohen",
    "Peter Do",
    "Peter Pilotto",
    "Petralux",
    "Peuterey",
    "PH5",
    "PHAEDO STUDIOS",
    "phaeonia",
    "Phaidon Press",
    "PHILEO",
    "Philip Karto",
    "Philipp Plein",
    "Philipp Plein Eyewear",
    "Philipp Plein Junior",
    "Philippe Model Paris",
    "Philo-Sofie",
    "Philosophy Di Lorenzo Serafini",
    "Philosophy di Lorenzo Serafini Eyewear",
    "Piaget",
    "Piazza Sempione",
    "PierAntonioGaspari",
    "Pierre Cardin Pre-Owned",
    "Pierre Hardy",
    "Pierre-Louis Mascia",
    "Pīferi",
    "Pineider",
    "Pinetti",
    "PINKO",
    "Pinto Paris",
    "Pippa Holt",
    "PIPPA SMALL",
    "Pippo Perez",
    "PIQUADRO",
    "Pitusa",
    "PIUMESTUDIO",
    "Plan C",
    "Plantation",
    "Pleasures",
    "Pleats Please Issey Miyake",
    "Plein Sport",
    "Plein Sud",
    "PNK",
    "POC",
    "Pollini",
    "Polly Wales",
    "Polo Ralph Lauren",
    "POLSPOTTEN",
    "Poltrona Frau",
    "Pomellato",
    "Pomellato Eyewear",
    "POMELLATO Pre-Owned",
    "PONTE VECCHIO",
    "POP SMOKE",
    "Pop Trading Company",
    "Poppy Finch",
    "Porsche Design",
    "Port Tanger",
    "Porter-Yoshida & Co.",
    "Ports 1961",
    "Ports V",
    "PortsPURE",
    "Post Archive Faction",
    "POSTER GIRL",
    "Poupette St Barth",
    "Prabal Gurung",
    "Prada",
    "Prada Eyewear",
    "Prada Linea Rossa",
    "Prada Pre-Owned",
    "Pragnell",
    "Pragnell Vintage",
    "Pre-Owned Alexander Wang",
    "Preciously",
    "Preen By Thornton Bregazzi",
    "Premiata",
    "Pretty Ballerinas",
    "Pringle of Scotland",
    "PRISM²",
    "Private 0204",
    "Proenza Schouler",
    "Proenza Schouler White Label",
    "Prounis",
    "Prune Goldschmidt",
    "PS Paul Smith",
    "PT Torino",
    "Pt01",
    "PUBLISHED BY",
    "PUCCI",
    "PUCCI Pre-Owned",
    "Pucci x Fusalp",
    "Pulpo",
    "PUMA",
    "Puppets and Puppets",
    "Puraai",
    "Purple Brand",
    "pushBUTTON",
    "Pyrenex",
    "Qasimi",
    "Qeeboo",
    "QUIRA",
    "Quire",
    "R.M.Williams",
    "R13",
    "raawii",
    "Rabanne",
    "Rabitti 1969",
    "Rachel Comey",
    "Rachel Gilbert",
    "Rachel Jackson",
    "RACIL",
    "RADA'",
    "Rado",
    "Raf Simons",
    "rag & bone",
    "RAG & BONE EYEWEAR",
    "RAGBAG STUDIO",
    "Rails",
    "Rains",
    "Ralph & Russo",
    "Ralph Lauren Collection",
    "Ralph Lauren Home",
    "Ralph Lauren RRL",
    "Ralph Vaessen",
    "Ramael",
    "Random Identities",
    "Rapha",
    "Raphaele Canot",
    "Rapp",
    "Rapport",
    "Raquel Allegra",
    "Raquel Diniz",
    "RASARIO",
    "Rave Review",
    "RAXXY",
    "Ray-Ban",
    "Rayane Bacha",
    "RE/DONE",
    "Readymade",
    "Rebecca Minkoff",
    "Rebecca Vallance",
    "Recreational Habits",
    "RED Valentino",
    "Red Wing Shoes",
    "RED(V)",
    "Redline",
    "REE PROJECTS",
    "Reebok",
    "Reebok LTD",
    "Reem Acra",
    "Reflections Copenhagen",
    "Reformation",
    "Reike Nen",
    "Reina Olga",
    "Rejina Pyo",
    "REMAIN",
    "René Boivin",
    "René Caovilla",
    "Renli Su",
    "Repossi",
    "Represent",
    "Retrofete",
    "Retrosuperfuture",
    "REV",
    "Rewind Vintage Affairs",
    "Rhea Costa",
    "Rhode",
    "RHODE",
    "RHUDE",
    "Rianna + Nina",
    "Richard Mille",
    "Richard Quinn",
    "Rick Owens",
    "Rick Owens DRKSHDW",
    "Rick Owens Lilies",
    "Rick Owens X Champion",
    "Rick Owens X VEJA",
    "Rier",
    "Rigards",
    "RITO STRUCTURE",
    "Rixo",
    "Rizzoli",
    "RJ Watches",
    "RLX Ralph Lauren",
    "ROA",
    "Robert Clergerie",
    "Roberta Einer",
    "Roberto Cavalli",
    "Roberto Cavalli Home",
    "Roberto Cavalli Junior",
    "Roberto Coin",
    "Roberto Collina",
    "Roberto Demeglio",
    "Roberto Festa",
    "Roberto Ricci Designs",
    "Rochas",
    "Rodarte",
    "Rodebjer",
    "Rodo",
    "Roger Dubuis",
    "Roger Vivier",
    "Róhe",
    "Rokh",
    "Roksanda",
    "Roland Mouret",
    "Rolex",
    "Rombaut",
    "Romeo Gigli Pre-Owned",
    "ROMEO HUNTE",
    "ROMUALDA",
    "Ronny Kobo",
    "Rosa Maria",
    "Rosantica",
    "Rose Carmine",
    "Roseanna",
    "Rosenthal",
    "Rosetta Getty",
    "Rosie Assoulin",
    "ROSIE KENT",
    "Rossignol",
    "ROTATE BIRGER CHRISTENSEN",
    "ROUGH.",
    "Rowen Rose",
    "Roxanne Assoulin",
    "Roxanne First",
    "ROZIE CORSETS",
    "RRD",
    "RTA",
    "RUI",
    "Ruifier",
    "RUN OF",
    "Rundholz",
    "Rupert Sanderson",
    "Rus",
    "Ruslan Baginskiy",
    "RXQUETTE",
    "S.T. Dupont",
    "S.W.O.R.D 6.6.44",
    "SA SU PHI",
    "Sabina Musayev",
    "SABOO FINE JEWELS",
    "sacai",
    "Sachin & Babi",
    "Safiyaa",
    "SafSafu",
    "SAGE NATION",
    "Saiid Kobeisy",
    "Saint Laurent",
    "Saint Laurent Eyewear",
    "Saint Laurent Pre-Owned",
    "SAINT MXXXXXX",
    "Saks Potts",
    "Salomon",
    "Saloni",
    "Salvatore Santoro",
    "Salvatori",
    "Samantha Sung",
    "Sambonet",
    "Sami Miro Vintage",
    "SAMSOE SAMSOE",
    "SAMUEL GUÌ YANG",
    "San Lorenzo",
    "Sandralexandra",
    "SANDRO",
    "Sankuanz",
    "Santa Brands",
    "Santangelo",
    "SANTHA",
    "Santoni",
    "SAPIO",
    "Sara Lanzi",
    "Sara Robertsson",
    "Sara Roka",
    "Sara Weinstock",
    "Sarah Chofakian",
    "Sargadelos",
    "Sartore",
    "Saskia Diez",
    "Satisfy",
    "Saucony",
    "SAULINA",
    "Save The Duck",
    "Savette",
    "Scarosso",
    "Schutz",
    "Scotch & Soda",
    "Sea",
    "Sease",
    "Sebago",
    "Sebastian Milano",
    "See by Chloé",
    "Seen Users",
    "Séfr",
    "Selasi",
    "Seletti",
    "Self-Portrait",
    "Selim Mouzannar",
    "Semicouture",
    "Semsem",
    "Sener Besim",
    "Sensi Studio",
    "Senso",
    "Serapian",
    "Serax",
    "Sergio Rossi",
    "Sergio Tacchini",
    "SERPUI",
    "Seventy",
    "Shamballa Jewels",
    "SHANG XIA",
    "Shanghai Tang",
    "Shanshan Ruan",
    "SHATHA ESSA",
    "Shaun Leane",
    "SHAY",
    "she's lost control",
    "sherris",
    "SHIATZY CHEN",
    "Shihara",
    "Shinkai",
    "Shinola",
    "Shoe The Bear",
    "Shona Joy",
    "Shoreditch Ski Club",
    "Shrimps",
    "SHUSHU/TONG",
    "Si Rossi",
    "Sia Taylor",
    "Sian Swimwear",
    "SICIS JEWELS",
    "SIEDRES",
    "SIEGER by FÜRSTENBERG",
    "Sies Marjan",
    "Silvano Sassetti",
    "SILVIA FURMANOVICH",
    "Silvia Tcherassi",
    "Simkhai",
    "Simkhai Standard",
    "Simon Miller",
    "Simone Rocha",
    "Simonetta Ravizza",
    "Simplehuman",
    "Sinead O'Dwyer",
    "SIR.",
    "SJP by Sarah Jessica Parker",
    "SJYP",
    "Skall Studio",
    "Skin",
    "Skultuna",
    "Sleeper",
    "SLVRLAKE",
    "Smeg",
    "SMFK",
    "Smythe",
    "Smythson",
    "Snob",
    "Snow Peak",
    "Société Anonyme",
    "Society",
    "Soeur",
    "SOFIA ZAKIA",
    "Sofie D'hoore",
    "Soho Home",
    "Sol Amor 1946",
    "Solace London",
    "Solid & Striped",
    "Something Wicked",
    "SOMI",
    "Song For The Mute",
    "SONGZIO",
    "Sonia Rykiel",
    "Sonora",
    "Sophia Webster",
    "Sophie Bille Brahe",
    "Sophie Buhai",
    "Sorayama",
    "Sorellina",
    "SORU",
    "Souliers Martinez",
    "Soulland",
    "Spalwart",
    "SPANX",
    "Spinelli Kilcollin",
    "Spoonyard",
    "SPORT b. by agnès b.",
    "Sportmax",
    "Sporty & Rich",
    "Sprung Frères",
    "Sprwmn",
    "SRVC Studio",
    "Ssheena",
    "St. Agni",
    "St. John",
    "STADIUM GOODS®",
    "Stain Shade",
    "STAND STUDIO",
    "STATEMENT PARIS",
    "Staub",
    "STAUD",
    "STEFANIA VAIDANI",
    "Stefano Mortari",
    "Stefere",
    "Stella Jean",
    "Stella McCartney",
    "Stella McCartney Eyewear",
    "Stella Nova",
    "STEPHANE ROLLAND",
    "Stephen Webster",
    "Stepney Workers Club",
    "Sterlé",
    "Sterling King",
    "Still Here",
    "Stine Goya",
    "Stockholm Surfboard Club",
    "Stolen Girlfriends Club",
    "Stone Island",
    "Stone Island Shadow Project",
    "Stone Paris",
    "Stories of Italy",
    "STORY mfg.",
    "Stouls",
    "Strathberry",
    "Stuart Weitzman",
    "Studio Amelia",
    "Studio Chofakian",
    "Studio Nicholson",
    "STUDIO TOMBOY",
    "Stüssy",
    "Stutterheim",
    "STYLAND",
    "Sueundercover",
    "Suicoke",
    "SUICOKE FUROSHIKI",
    "SUICOKE VFF",
    "Suicoke x Palm Angels",
    "sulvam",
    "Sun 68",
    "Sunnei",
    "SUOT STUDIO",
    "Super Duper Hats",
    "Superga",
    "Superplastic",
    "Suprema",
    "Supreme",
    "Supriya Lele",
    "Susan Caplan Vintage",
    "Susan Fang",
    "Susana Vega",
    "Suzanne Kalan",
    "Suzanne Rae",
    "Suzusan",
    "Swarovski",
    "Swayta sha",
    "SWEAR",
    "Sweaty Betty",
    "Sydney Evan",
    "Sylva & Cie",
    "Sylvia Toledano",
    "Sylvie Schimmel",
    "System",
    "T Henri Eyewear",
    "Tabayer",
    "TABITHA RINGWOOD",
    "Tadashi Shoji",
    "TAG Heuer",
    "TAG Heuer Pre-Owned",
    "Tagliatore",
    "Takahiromiyashita The Soloist",
    "Takashi Murakami",
    "Talbot Runhof",
    "Talia Byre",
    "Taller Marmo",
    "TAMARA COMOLLI",
    "Tamara Taichman",
    "TAMMY & BENJAMIN",
    "Tanya Taylor",
    "Tara Matthews",
    "Tartine Et Chocolat",
    "TASAKI",
    "TASCHEN",
    "Tata Christiane",
    "Tateossian",
    "Tatras",
    "TEAM WANG design",
    "Ted Baker",
    "Teddy Cashmere",
    "TEKLA",
    "Tela",
    "Telfar",
    "Telfar Pre-Owned",
    "Temperley London",
    "Templa",
    "Ten Thousand Things",
    "The 2Nd Skin Co.",
    "THE ALKEMISTRY",
    "THE ANDAMANE",
    "The Animals Observatory",
    "The Attico",
    "The Beatles X Comme Des Garçons",
    "The Bridge",
    "The Elder Statesman",
    "The Frankie Shop",
    "THE FREYA BRAND",
    "THE GIVING MOVEMENT",
    "The Great.",
    "The House of Lyria",
    "The Mannei",
    "The Marc Jacobs",
    "The New Arrivals Ilkyaz Ozel",
    "The North Face",
    "The Row",
    "THE SADDLER",
    "The Seafarer",
    "The Upside",
    "The Vampire's Wife",
    "Thebe Magugu",
    "Themis Z",
    "Themoirè",
    "Theo Eyewear",
    "Theory",
    "There Was One",
    "Thierry Lasry",
    "Thierry Mugler Pre-Owned",
    "THIRD CROWN",
    "Thom Browne",
    "Thom Browne Eyewear",
    "Thom Krom",
    "Three Graces",
    "Throwback.",
    "Tiba + Marl",
    "Tibi",
    "Tiffany & Co Eyewear",
    "Tiffany & Co. Pre-Owned",
    "Tila March",
    "Timberland",
    "TIMEX",
    "Tod's",
    "Toga",
    "Toga Pulla",
    "Tohum",
    "Tom Binns",
    "Tom Dixon",
    "TOM FORD",
    "TOM FORD Eyewear",
    "Tom Wood",
    "Tommy Hilfiger",
    "Tommy Jeans",
    "Toogood",
    "Tori Solea",
    "Tory Burch",
    "TOTEME",
    "TOUCHLESS",
    "tout a coup",
    "TOVE",
    "Transit",
    "Transparent",
    "Travis Scott",
    "Tricker's",
    "Trippen",
    "Troubadour",
    "TRUDON",
    "True Rocks",
    "Trussardi",
    "Tsatsas",
    "TSAU",
    "TTSWTRS",
    "Tu es mon Tresor",
    "TU LIZE'",
    "tubici",
    "TUDOR",
    "Tuinch",
    "Twenty Montreal",
    "TWINSET",
    "TWP",
    "Tyler Ellis",
    "U-Boat",
    "U-Mask",
    "U.P.W.W.",
    "UGG",
    "UGG Kids",
    "Ugo Paulon",
    "Ulla Johnson",
    "Ulyana Sergeenko",
    "Ulysse Nardin",
    "Uma | Raquel Davidowicz",
    "Uma Wang",
    "Uncommon Matters",
    "Under Armour",
    "Undercover",
    "Uniform Wares",
    "unimatic",
    "United Nude",
    "UNRAVEL PROJECT",
    "Unreal Fur",
    "Urbancode",
    "URSA",
    "Utopia & Utility",
    "V:PM ATELIER",
    "V°73",
    "Vaara",
    "Vacheron Constantin",
    "Valentino Eyewear",
    "Valentino Garavani",
    "Valentino Garavani Pre-Owned",
    "Valextra",
    "VAMSKO",
    "Van Cleef & Arpels",
    "Van Cleef & Arpels Vintage",
    "Van Palma",
    "Vanda Jacintho",
    "Vanessa Mitrani",
    "Vanina",
    "Vann Jewelry",
    "Vanrycke",
    "Vans",
    "Vaquera",
    "Varley",
    "Vasic",
    "VAVA Eyewear",
    "VeeCollective",
    "VEJA",
    "Venini",
    "Vera Wang",
    "Veronica Beard",
    "Veronique Leroy",
    "Versace",
    "Versace Eyewear",
    "Versace Jeans Couture",
    "Versace Pre-Owned",
    "VETEMENTS",
    "VEYNOU",
    "VFILES",
    "Via Roma 15",
    "Vibe Harsløf",
    "Vic Matie",
    "Vicedomini",
    "Victoria Beckham",
    "Victoria Beckham Eyewear",
    "Victoria Victoria Beckham",
    "Viktor & Rolf",
    "Vilebrequin",
    "VILLARI",
    "Villeroy & Boch",
    "Vince",
    "VINNY'S",
    "Virón",
    "Vision Of Super",
    "Vista Alegre",
    "visvim",
    "Vita Kin",
    "VITELLI",
    "Vitra",
    "Vivetta",
    "Vivienne Westwood",
    "Vivienne Westwood Pre-Owned",
    "Vogue Eyewear",
    "VOZ",
    "VTMNTS",
    "Vuarnet",
    "Wacoal",
    "Waimari",
    "Waiwai Rio",
    "Wales Bonner",
    "Walk Of Shame",
    "Walter Van Beirendonck",
    "Walter Van Beirendonck Pre-Owned",
    "Wandering",
    "Wandler",
    "WARDROBE.NYC",
    "Warm-Me",
    "Washington Dee Cee",
    "Wästberg",
    "We Are Kindred",
    "We by WHITEbIRD",
    "We Norwegians",
    "We11done",
    "Weekend Max Mara",
    "Weinsanto",
    "WERKSTATT:MÜNCHEN",
    "WESTFALL",
    "White Mountaineering",
    "Wild Cashmere",
    "Wilhelmina Garcia",
    "Windsor",
    "WOERA",
    "Wolford",
    "Woolrich",
    "Wooyoungmi",
    "Wouters & Hendrix",
    "Wouters & Hendrix Gold",
    "WTAPS",
    "WWAKE",
    "Xacus",
    "Xander Zhou",
    "XLBoom",
    "XOCOI",
    "Y-3",
    "Y's",
    "Y/Project",
    "Yang Li",
    "Yannis Sergakis",
    "YANYAN KNITS",
    "YASSMIN SALEH",
    "YELLOW PLUS",
    "Yeprem",
    "YMC",
    "Yohji Yamamoto",
    "Yohji Yamamoto Pre-Owned",
    "Yoko London",
    "YOSSI HARARI",
    "Youths In Balaclava",
    "YSL",
    "Yu Mei",
    "Yueqi Qi",
    "yuhan wang",
    "Yuiki Shimoji",
    "Yuliya Magdych",
    "YUME YUME",
    "Yuzefi",
    "Yves Saint Laurent Pre-Owned",
    "Yves Salomon",
    "Yvonne Léon",
    "Zac Posen",
    "Zac Zac Posen",
    "Zadig&Voltaire",
    "Zaha Hadid Design",
    "Zanat",
    "Zanellato",
    "Zanone",
    "ZEEMOU ZENG",
    "Zegna",
    "Zenith",
    "Zeus+Dione",
    "ZEYNEP ARCAY",
    "Ziggy Chen",
    "ZIMMERMANN",
    "Zoë Chicco",
    "ZSIGMOND",
    "Zuhair Murad",
    "Zwilling",
    "ZZERO BY SONGZIO",
    "Château Lafleur-Gazin",
    "IVY OAK",
    "RASSVET",
    "'S Max Mara",
    "(di)vision",
    "*BABY MILO® STORE BY *A BATHING APE®",
]

const mostPopularBrands = [
    "Nike",
    "Adidas",
    "Sin Marca",
    "Marca nacional",
]

function convertArrayToJSON(array:Array<string>) {
    return array.map(name => ({
        name: name,
        value: name.toLowerCase().replace(/\s+/g, '')
    }));
}

export const brands = convertArrayToJSON(arr)

export const mostPopularBrandsJSON = convertArrayToJSON(mostPopularBrands)
